preload = /home/carles/.config/hypr/wallpapers/Doodle_Space_Nord.png

wallpaper {
    monitor = DP-1
    path = /home/carles/.config/hypr/wallpapers/Doodle_Space_Nord.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/carles/.config/hypr/wallpapers/Doodle_Space_Nord.png
    fit_mode = cover
}

