preload = /home/carles/.config/hypr/wallpapers/3840x2160-nausica%C3%A4-of-the-valley-of-the-wind-v0-5s01xlcz398h1.png

wallpaper {
    monitor = eDP-1
    path = /home/carles/.config/hypr/wallpapers/3840x2160-nausica%C3%A4-of-the-valley-of-the-wind-v0-5s01xlcz398h1.png
    fit_mode = cover
}

